### ISSUE TITLE
Does not work from subdirectories

### ISSUE THREAD

**Issue by gturri** [anvaka/git-also#5]
Git-also is a rather cool software! I just have a feature request, to make it even better: make it work from subdirectories.

In more details, let's say I have a file in `src/myFile.js`. If I run from the root of the repo, the command `git also src/myFiles.js`, it works correctly (ie: it displays the similarity).
But if I run

    cd src
    git also myFile.js

then it doesn't display anything, which
* is counter-intuitive (it took me some time to understand why I didn't had any results, because almost all git command work well from subdirectories)
* makes `git also` less easy to use

**Comment by anvaka** [comment]
Thanks!

This should be fixed in `v1.0.5`. Please run `npm update -g git-also` and try it again. Does it work?

**Comment by gturri** [comment]
It works perfectly fine! Thanks for developing it so quickly!
