### ISSUE TITLE
git-also died of signal 6

### ISSUE THREAD

**Issue by cdsap** [anvaka/git-also#6]
Hi, 
I'm trying git also with our project and I'm getting:

```
<--- Last few GCs --->

   11245 ms: Scavenge 1356.0 (1435.0) -> 1355.9 (1435.0) MB, 5.5 / 0 ms (+ 0.3 ms in 1 steps since last GC) [allocation failure].
   11251 ms: Scavenge 1355.9 (1435.0) -> 1356.0 (1435.0) MB, 5.4 / 0 ms [allocation failure].
   12022 ms: Mark-sweep 1356.0 (1435.0) -> 1355.5 (1435.0) MB, 771.0 / 0 ms (+ 700.5 ms in 1268 steps since start of marking, biggest step 2.3 ms) [last resort gc].
   12683 ms: Mark-sweep 1355.5 (1435.0) -> 1355.5 (1435.0) MB, 661.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x7fc892c9fa9 <JS Object>
    1: processOtherFile [/usr/local/lib/node_modules/git-also/lib/computeSimilarities.js:~68] [pc=0x33da71ac33c] (this=0x7fc892e99d9 <JS Global Object>,fileB=0x12aeee638a59 <String[60]: ui-core/src/main/res/drawable-xxhdpi/antigua_and_barbuda.png>)
    2: arguments adaptor frame: 3->1
    3: InnerArrayForEach(aka InnerArrayForEach) [native array.js:~946] [pc=0x33da71a6d45] (this=0x7fc89204189 <u...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
error: git-also died of signal 6

```

The project is big. Maybe I have something wrong in my set up?

Thanks

**Comment by anvaka** [comment]
## short version

```
# edit your instance of git-also
GIT_ALSO_PATH=`which git-also`
vim $GIT_ALSO_PATH
```

Change first line from

```
#!/usr/bin/env node
```

to
``` 
#!/usr/bin/env node --max_old_space_size=4096
```

Save file and try again.

## Longer version

By the look of the stack trace, the process is running out of maximum `v8` memory limit.

This limit is usually smaller than available system memory and depend on node version and system architecture (32 bit vs 64 bit). I know on 64 bit systems this limit is around 1.7GB. I don't have 32 bit version, but googling around suggests it's capped at ~1.4 GB. 

Depending on your situation you can try 64 bit version of node (if your system is 64 bit). Or increase memory limit of `v8` engine (if your system has more than 1.4 GB of RAM). 

To increase the memory limit you need to pass `--max_old_space_size` option to node, as suggested above.

**Comment by cdsap** [comment]
Hi @anvaka 
Thank you very much  for the response. 
Now is working, I increased memory limit as you said and everything ok. 

Thanks again
